{% set name = "neptune-notebooks" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/neptune-notebooks/archive/{{ version }}.tar.gz
  sha256: d65fa82aa54a2e7e64f5d40389817eed0140ae22406e44d06f9d41fa107d2a27

build:
  noarch: python
  number: 0
  entry_points:
    - neptune_notebooks = neptune_notebooks_plugin:notebook
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - nodejs
    - openjdk
  run:
    - python
    - click >=7.0
    - future >=0.17.1
    - neptune-client >=0.4.92
    - notebook >=4.3.0
    - path.py

test:
  imports:
    - neptune_notebooks

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune's integration with Jupiter and JupiterLab notebooks
  doc_url: https://docs.neptune.ai
  dev_url: https://github.com/neptune-ai/neptune-notebooks

extra:
  recipe-maintainers:
    - szymon-kuklewicz
    - aniezurawski
    - hubertjaworskineptune
    - pitercl
