{% set name = "neptune-notebooks" %}
{% set version = "0.0.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/neptune-ai/neptune-notebooks/archive/{{ version }}.tar.gz"
  sha256: 94900d82b0b846a132ab416486cf30456c19d5a3198bd4d9c93e4da681fe9322

build:
  noarch: python
  number: 0
  entry_points:
    - neptune_notebooks = neptune_notebooks_plugin:notebook
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - nodejs
    - openjdk
  run:
    - python
    - click >=7.0
    - future >=0.17.1
    - neptune-client >=0.4.92
    - notebook >=4.3.0
    - path.py

test:
  imports:
    - neptune_notebooks
    - tests.neptune_notebooks
    - tests.neptune_notebooks_plugin

about:
  home: "https://neptune.ai/"
  license: Apache-2.0
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "Neptune's integration with Jupiter and JupiterLab notebooks"
  doc_url: "https://docs.neptune.ai"
  dev_url: "https://github.com/neptune-ai/neptune-notebooks"

extra:
  recipe-maintainers:
    - szymon-kuklewicz
    - aniezurawski
    - hubertjaworskineptune
    - pitercl
